Tried to correct for missing buttons.py
File "/home/pi/rpi_wordclock/wordclock_plugins/time_matrix/plugin.py",
line 6, in <module>
import wordclock_tools.buttons as wcb
ImportError: No module named buttons